name = "vinegar-forge-edition"
author = "VinegarHQ"
version = "3.6.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "a09f408f450402f989120eeca58f927c51bbd2ad923a40ea5563c9588c8bb04b"

[versions]
forge = "14.23.5.2860"
minecraft = "1.12.2"
