name = "vinegar-forge-edition"
author = "VinegarHQ"
version = "3.6.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "f13188f7bb560df7f9e8408748ab0af509942b5a5d60785acd899aff1a41695e"

[versions]
forge = "14.23.5.2860"
minecraft = "1.12.2"
