name = "vinegar-forge-edition"
author = "VinegarHQ"
version = "3.6.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "cc808eb0c0e238160eed4cfa974a9c6ab76ca208eb0bb875082c23703411e5c7"

[versions]
forge = "14.23.5.2860"
minecraft = "1.12.2"
