name = "ftb-revelation"
author = "FTB Team"
version = "3.6.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "681e0e06b7c198384606f9140c326e0499d4e729930a809ee53eeffefc729dd0"

[versions]
forge = "14.23.5.2860"
minecraft = "1.12.2"
